### ISSUE TITLE
サムネイルにスクロールバーがでる

### ISSUE THREAD

**Issue by pumpkinheader** [daicche/quiche_issues#37]
前のキッシュみたいになってる・・！きれい！！
サムネイルにスクロールバー表示されてるのだけれど、画像サイズに関係なく出てるような？
## 表題の件はこんなかんじです

![2016-06-03 1](https://cloud.githubusercontent.com/assets/6647001/15770465/e8e77f6e-299e-11e6-8b73-c3e688064604.png)
## CSS

CSS覗いたら、

``` css
.contents .row .column_right .thumbnail {
    /* 略 */
    overflow: scroll;
}
```

ってなってたのでとりあえずは仕様？
## 応急

`overflow: hidden`
にすれば消える。他への影響はわかりませぬ。。
そもそも意図した挙動なら済まぬ。
## バージョンなど

Win10版 Chrome 51.0.2704.79 m (64-bit)
